//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.25 at 03:35:22 CST
//


package com.dongfeng.study.bean.ota.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 编码之前的xml格式请求里面的header部分
 *
 * @author eastFeng
 * @date 2020-12-07 20:22
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtaRequestHeader", propOrder = {
    "application",
    "processor",
    "version",
    "bodyType",
    "createUser",
    "createTime",
    "supplierIdentity"
})
public class OtaRequestHeader {

    /**
     * 系统版本
     * tour.ectrip.com  不变
     */
    @XmlElement(required = true)
    private String application;

    /**
     * 处理程序
     * DataExchangeProcessor 不变
     */
    @XmlElement(required = true)
    private String processor;

    /**
     * 版本
     * v1.0.0 不变
     */
    @XmlElement(required = true)
    private String version;

    /**
     * 消息体类型：依据BodyType实际类型填写
     */
    @XmlElement(required = true)
    private String bodyType;

    /**
     * 创建用户：分销商用户名
     */
    @XmlElement(required = true)
    private String createUser;

    /**
     * 创建时间
     * yyyy-MM-dd HH:mm:ss
     */
    @XmlElement(required = true)
    private String createTime;

    /**
     * 供应商用户名
     */
    @XmlElement(required = true)
    private String supplierIdentity;

    /**
     * Gets the value of the application property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setApplication(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the processor property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setProcessor(String value) {
        this.processor = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the bodyType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBodyType() {
        return bodyType;
    }

    /**
     * Sets the value of the bodyType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBodyType(String value) {
        this.bodyType = value;
    }

    /**
     * Gets the value of the createUser property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * Sets the value of the createUser property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreateUser(String value) {
        this.createUser = value;
    }

    /**
     * Gets the value of the createTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreateTime(String value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the supplierIdentity property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSupplierIdentity() {
        return supplierIdentity;
    }

    /**
     * Sets the value of the supplierIdentity property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSupplierIdentity(String value) {
        this.supplierIdentity = value;
    }

}
